export const qualifications = [
  {"id": 1 ,  "active" : false ,name: 'Background Check' },
  {"id": 2 ,  "active" : false ,name: 'Certification' },
  {"id": 3 ,  "active" : false ,name: "Driver's License" },
  {"id": 4 ,  "active" : false ,name: 'Drug Test' },
  {"id": 5 ,  "active" : false ,name: 'Education' },
  {"id": 6 ,  "active" : false ,name: 'Expertise with Skill' },
  {"id": 7 ,  "active" : false ,name: 'GPA' },
  {"id": 8 ,  "active" : false ,name: 'Hybrid Work' },
  {"id": 9 ,  "active" : false ,name: 'Industry Experience' },
  {"id": 10 , "active" : false , name: 'Language' },
  {"id": 11 , "active" : false , name: 'Location' },
  {"id": 12 , "active" : false , name: 'Onsite Work' },
  {"id": 13 , "active" : false , name: 'Remote Work' },
  {"id": 14 , "active" : false , name: 'Urgency' },
  {"id": 15 , "active" : false , name: 'Visa Status' },
  {"id": 16 , "active" : false , name: 'Work Authorization' },
  {"id": 17 , "active" : false , name: 'Work Experience' },
  {"id": 18 , "active" : false , name: 'Custom Qualifications' },
]

export const screeningQuestions = [
  {"id": 1,  "active" : false,name: 'Are you willing to undergo a background check, in accordance with local law/regulations?'},
  {"id": 2,  "active" : false,name: 'Do you have the following license or certification: [License/Certification]?', "leftSide": 'License/Certification'},
  {"id": 3,  "active" : false,name: "Do you have a valid driver's license?"},
  {"id": 4,  "active" : false,name: 'Are you willing to take a drug test, in accordance with local law/regulations?'},
  {"id": 5,  "active" : false,name: 'Have you completed the following level of education: [Degree]?', "leftSide": 'Degree'},
  {"id": 6,  "active" : false,name: 'How many years of work experience do you have with [Skill]?', "leftSide": 'Skill', "rightSide": "Ideal answer (minimum):"},
  {"id": 7,  "active" : false,name: 'What is your university grade point average (4.0 GPA Scale)?', "leftSide": "Ideal answer (minimum):"},
  {"id": 8,  "active" : false,name: 'Are you comfortable working in a hybrid setting?'},
  {"id": 9,  "active" : false,name: 'How many years of [Industry] experience do you currently have?', "leftSide": 'Industry', "rightSide": "Ideal answer (minimum):"},
  {"id": 10, "active" : false, name: 'What is your level of proficiency in [Language]?', "leftSide": 'Language', "rightSide": "Ideal answer"},
  {"id": 11, "active" : false, name: "Are you comfortable commuting to this job's location?"},
  {"id": 12, "active" : false, name: 'Are you comfortable working in an onsite setting?'},
  {"id": 13, "active" : false, name: 'Are you comfortable working in a remote setting?'},
  {"id": 14, "active" : false, name: 'We must fill this position urgently. Can you start immediately?'},
  {"id": 15, "active" : false, name: 'Will you now, or in the future, require sponsorship for employment visa status (e.g. H-1B visa status)?', "idealAnswer": "No"},
  {"id": 16, "active" : false, name: 'Are you legally authorized to work in the United States?'},
  {"id": 17, "active" : false, name: 'How many years of [Job Function] experience do you currently have?', "leftSide": 'Job Function', "rightSide": "Ideal answer (minimum):"},
  {"id": 18, "active" : false, name: 'Write a custom screening question.'},
]